theme: jekyll-theme-cayman
title: Roy Jackman
description: Computer Scientist for hire

footer-links:
  email: jackman.roy@gmail.com
  github: royJackman

google_analytics: UA-124477413-1

permalink: /:title/

version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded

gems:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME